'use strict';
module.exports = {
  welcome: '\'Allo \'allo! Out of the box I include Node, Typescript, Jasmine, Karma, Gulp tasks and many other features to build your app.',
  generator: 'You\'re using the fantastic TypeScript NPM Bower generator.',
  travis: 'Include travis config',
  boilerplate: 'Include boilerplate files',
  gulp: 'Include or not a gulpfile.js',
  license: 'Include a license',
  name: 'Project name',
  description: 'Description',
  homepage: 'Project homepage url',
  authorName: 'Author\'s Name',
  authorEmail: 'Author\'s Email',
  authorUrl: 'Author\'s Homepage',
  keywords: 'Keywords to search your package (comma to split)',
  githubAccount: 'GitHub username or organization',
  projectRoot: 'Relative path to the project code root',
  readme: 'Content to insert in the README.md file',
  browser: 'Do you want a browser compatible module?',
  styles: 'Do you need to include styles?',
  scss: 'Do you like to use SCSS extension?',
  bower: 'Do you like to use this as a bower component?',
  generateInto: 'Relocate the location of the generated files.',
  testFramework: 'Which test framework would you like to use?'
};
