'use strict';
module.exports = {
  welcome: '\'Allo \'allo! Out of the box I include Node, Typescript, Jasmine, Mocha, Chai, Karma, Gulp tasks and many other features to build your app.',
  generator: 'You\'re using the fantastic TypeScript NPM Bower generator.',
  travis: 'Include travis config',
  boilerplate: 'Include boilerplate files',
  gulp: 'Include or not a gulpfile.js',
  license: 'Select the type of the license you like to use',
  name: 'What is the name of your module?',
  description: 'What is the description of your module?',
  homepage: 'Project homepage url',
  authorName: 'What is the Author\'s Name?',
  authorEmail: 'What is the Author\'s Email',
  authorUrl: 'What is the Author\'s Homepage',
  keywords: 'Keywords to search your package (comma to split)',
  githubAccount: 'What is your username or organization',
  projectRoot: 'Relative path to the project code root',
  readme: 'Content to insert in the README.md file',
  browser: 'Do you want a client (browser compatible) node module?',
  styles: 'Do you need to include styles?',
  scss: 'Do you like to use SCSS extension?',
  bower: 'Do you want to include bower component?',
  generateInto: 'Relocate the location of the generated files.',
  testFramework: 'Which test framework would you like to use?'
};
